language: node_js
sudo: false
node_js:
  - 'stable'

addons:
  sauce_connect: true

cache:
  directories:
    - node_modules

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  #- npm start > /dev/null &
  - sleep 1

script:
  - gulp --require coffee-script/register lint
  - karma start karma.conf.coffee
  - gulp --require coffee-script/register build-e2e

after_success:
  - npm install coveralls && cat ./coverage/**/lcov.info | coveralls
