language: node_js
node_js:
  - stable

cache:
  directories:
    - node_modules

before_script:
  - npm install karma-firefox-launcher
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c webdriver-manager start 2>&1 &
  - sleep 1

script:
  - gulp --require coffee-script/register lint
  - gulp --require coffee-script/register unit
  - gulp --require coffee-script/register e2e
