language: node_js
node_js:
  - '4'
  - '5'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - webdriver-manager update
  - sleep 1

script:
  - karma start karma.conf.coffee --single-run --browsers=Firefox
  - protractor protractor.conf.coffee --browser=firefox

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
