language: node_js
node_js:
  - '4'
  - '5'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - sleep 1

script:
  - npm run lint
  - npm run unit
#  - npm run e2e  # Sauce Labs

after_success:
  - npm run coverage
