language: node_js
node_js:
  - 'stable'

cache:
  directories:
    - node_modules

script:
  - gulp --require coffee-script/register lint
  - gulp --require coffee-script/register unit
  - gulp --require coffee-script/register e2e
