language: node_js
sudo: false
node_js:
  - '4'
  - 'stable'

env:
  global:
    - SAUCE_USERNAME=Shyam-Chen
    - SAUCE_ACCESS_KEY=c3608032-6eff-452e-9027-602ca80a8778

addons:
  sauce_connect: true

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./public &
  - sleep 1

script:
  - gulp --require coffee-script/register lint
  - karma start karma.conf.coffee
  - gulp --require coffee-script/register build-e2e

after_success:
  - npm install coveralls && cat ./coverage/**/lcov.info | coveralls
