language: node_js
sudo: false
node_js:
  - '4'
  - '5'

addons:
  sauce_connect: true

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - sleep 1

script:
  - gulp --require coffee-script/register lint
  - karma start karma.conf.coffee --single-run
  - gulp --require coffee-script/register build-e2e

after_success:
  - cat ./coverage/**/lcov.info | ./node_modules/.bin/coveralls
