language: node_js
sudo: false
node_js:
  - 'stable'

addons:
  sauce_connect: true

cache:
  directories:
    - node_modules

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - npm install shelljs
  - sh -e /etc/init.d/xvfb start
  - sleep 1

script:
  - gulp --require coffee-script/register lint
  - gulp --require coffee-script/register unit
  - gulp --require coffee-script/register e2e

after_success:
  - npm install coveralls && cat ./coverage/**/lcov.info | coveralls
